Repository Jungdaye89/chone, pull requests merged in 2025-02, with the labels that each got.

#6 Feat: Global Exception Handler 구현
  .gitmessage.txt
  build.gradle
  src/main/java/com/chone/server/commons/exception/ApiBusinessException.java
  src/main/java/com/chone/server/commons/exception/ExceptionCode.java
  src/main/java/com/chone/server/commons/exception/GlobalExceptionCode.java
  src/main/java/com/chone/server/commons/exception/dto/ExceptionResponse.java
  src/main/java/com/chone/server/commons/handler/GlobalExceptionHandler.java
  src/test/java/com/chone/server/commons/exception/mock/MockApiExceptionCode.java
  src/test/java/com/chone/server/commons/handler/GlobalExceptionHandlerTest.java
Labels: ❤️‍🔥Feat, ⚗️Test

#12 Feat: UserEntity & RoleEnum 생성 및 추가
  src/main/java/com/chone/server/domains/user/domain/Role.java
  src/main/java/com/chone/server/domains/user/domain/User.java
Labels: ❤️‍🔥Feat

#13 Feat: Ai, Review Entity 설계
  src/main/java/com/chone/server/domains/ai/domain/entity/Ai.java
  src/main/java/com/chone/server/domains/review/domain/entity/Review.java
Labels: ❤️‍🔥Feat

#17 Feature: Order 및 Payment Entity 설계
  src/main/java/com/chone/server/domains/order/domain/Order.java
  src/main/java/com/chone/server/domains/order/domain/OrderItem.java
  src/main/java/com/chone/server/domains/order/domain/OrderStatus.java
  src/main/java/com/chone/server/domains/order/domain/OrderType.java
  src/main/java/com/chone/server/domains/payment/domain/Payment.java
  src/main/java/com/chone/server/domains/payment/domain/PaymentMethod.java
  src/main/java/com/chone/server/domains/payment/domain/PaymentStatus.java
  src/main/java/com/chone/server/domains/user/domain/User.java
Labels: ❤️‍🔥Feat

#15 Feat: store, product entity 설계
  .gitignore
  build.gradle
  src/main/java/com/chone/server/commons/config/QuerydslConfig.java
  src/main/java/com/chone/server/commons/exception/GlobalExceptionCode.java
  src/main/java/com/chone/server/domains/product/domain/Product.java
  src/main/java/com/chone/server/domains/store/controller/StoreController.java
  src/main/java/com/chone/server/domains/store/domain/Category.java
  src/main/java/com/chone/server/domains/store/domain/LegalDongCode.java
  src/main/java/com/chone/server/domains/store/domain/Store.java
  src/main/java/com/chone/server/domains/store/domain/StoreCategoryMap.java
  src/main/java/com/chone/server/domains/store/dto/request/CreateRequestDto.java
  src/main/java/com/chone/server/domains/store/dto/request/PutRequestDto.java
  src/main/java/com/chone/server/domains/store/dto/response/CreateResponseDto.java
  src/main/java/com/chone/server/domains/store/dto/response/PageInfoDto.java
  src/main/java/com/chone/server/domains/store/dto/response/ReadResponseDto.java
  src/main/java/com/chone/server/domains/store/dto/response/SearchResponseDto.java
  src/main/java/com/chone/server/domains/store/exception/StoreExceptionCode.java
  src/main/java/com/chone/server/domains/store/repository/CategoryRepository.java
  src/main/java/com/chone/server/domains/store/repository/LegalDongCodeRepository.java
  src/main/java/com/chone/server/domains/store/repository/StoreCategoryMapRepository.java
  src/main/java/com/chone/server/domains/store/repository/StoreRepository.java
  src/main/java/com/chone/server/domains/store/repository/custom/StoreRepositoryCustom.java
  src/main/java/com/chone/server/domains/store/repository/custom/StoreRepositoryCustomImpl.java
  src/main/java/com/chone/server/domains/store/service/StoreService.java
Labels: ❤️‍🔥Feat

#35 Feat: Product CRUD API 설계
  src/main/java/com/chone/server/domains/product/controller/ProductController.java
  src/main/java/com/chone/server/domains/product/domain/Product.java
  src/main/java/com/chone/server/domains/product/dto/request/CreateRequestDto.java
  src/main/java/com/chone/server/domains/product/dto/request/UpdateRequestDto.java
  src/main/java/com/chone/server/domains/product/dto/response/CreateResponseDto.java
  src/main/java/com/chone/server/domains/product/dto/response/PageInfoDto.java
  src/main/java/com/chone/server/domains/product/dto/response/ReadResponseDto.java
  src/main/java/com/chone/server/domains/product/dto/response/SearchResponseDto.java
  src/main/java/com/chone/server/domains/product/exception/ProductExceptionCode.java
  src/main/java/com/chone/server/domains/product/repository/ProductRepository.java
  src/main/java/com/chone/server/domains/product/repository/custom/ProductRepositoryCustom.java
  src/main/java/com/chone/server/domains/product/repository/custom/ProductRepositoryCustomImpl.java
  src/main/java/com/chone/server/domains/product/service/ProductService.java
  src/main/java/com/chone/server/domains/store/dto/request/CreateRequestDto.java
Labels: ❤️‍🔥Feat

#38 Feat: Ai 요청 API 생성
  src/main/java/com/chone/server/commons/jpa/BaseEntity.java
  src/main/java/com/chone/server/domains/ai/controller/AiController.java
  src/main/java/com/chone/server/domains/ai/domain/Ai.java
  src/main/java/com/chone/server/domains/ai/dto/request/AiRequestDto.java
  src/main/java/com/chone/server/domains/ai/dto/request/GeminiApiRequestDto.java
  src/main/java/com/chone/server/domains/ai/dto/request/GeminiRequestDto.java
  src/main/java/com/chone/server/domains/ai/dto/response/AiResponseDto.java
  src/main/java/com/chone/server/domains/ai/dto/response/GeminiApiResponseDto.java
  src/main/java/com/chone/server/domains/ai/dto/response/GeminiResponseDto.java
  src/main/java/com/chone/server/domains/ai/exception/AiExceptionCode.java
  src/main/java/com/chone/server/domains/ai/repository/AiRepository.java
  src/main/java/com/chone/server/domains/ai/service/AiService.java
  src/main/java/com/chone/server/domains/product/domain/Product.java
  src/main/java/com/chone/server/domains/product/repository/ProductRepository.java
  src/main/java/com/chone/server/domains/review/domain/Review.java
  src/main/java/com/chone/server/domains/user/domain/User.java
Labels: ❤️‍🔥Feat

#40 Feat: 주문 생성(Create) 구현
  src/main/java/com/chone/server/ChoneApplication.java
  src/main/java/com/chone/server/commons/config/JpaConfig.java
  src/main/java/com/chone/server/commons/exception/GlobalExceptionCode.java
  src/main/java/com/chone/server/commons/jpa/AuditorAwareImpl.java
  src/main/java/com/chone/server/commons/util/UriGeneratorUtil.java
  src/main/java/com/chone/server/domains/order/controller/OrderController.java
  src/main/java/com/chone/server/domains/order/domain/Delivery.java
  src/main/java/com/chone/server/domains/order/domain/Order.java
  src/main/java/com/chone/server/domains/order/domain/OrderItem.java
  src/main/java/com/chone/server/domains/order/domain/OrderStatus.java
  src/main/java/com/chone/server/domains/order/domain/vo/Price.java
  src/main/java/com/chone/server/domains/order/domain/vo/Quantity.java
  src/main/java/com/chone/server/domains/order/dto/request/CreateOrderRequest.java
  src/main/java/com/chone/server/domains/order/dto/response/CreateOrderResponse.java
  src/main/java/com/chone/server/domains/order/exception/OrderExceptionCode.java
  src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderJpaRepository.java
  src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderRepositoryImpl.java
  src/main/java/com/chone/server/domains/order/repository/OrderRepository.java
  src/main/java/com/chone/server/domains/order/service/OrderDomainService.java
  src/main/java/com/chone/server/domains/order/service/OrderService.java
  src/main/java/com/chone/server/domains/product/service/ProductService.java
  src/main/java/com/chone/server/domains/store/service/StoreService.java
  src/main/java/com/chone/server/domains/user/domain/User.java
Labels: ❤️‍🔥Feat

#52 Feat: 주문 상세 조회 기능 구현
  src/main/java/com/chone/server/domains/order/controller/OrderController.java
  src/main/java/com/chone/server/domains/order/domain/vo/Quantity.java
  src/main/java/com/chone/server/domains/order/dto/request/CreateOrderRequest.java
  src/main/java/com/chone/server/domains/order/dto/response/CreateOrderResponse.java
  src/main/java/com/chone/server/domains/order/dto/response/OrderDetailResponse.java
  src/main/java/com/chone/server/domains/order/exception/OrderExceptionCode.java
  src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderDetailSearchRepositoryImpl.java
  src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderListSearchRepositoryImpl.java
  src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderRepositoryImpl.java
  src/main/java/com/chone/server/domains/order/repository/OrderDetailSearchRepository.java
  src/main/java/com/chone/server/domains/order/repository/OrderListSearchRepository.java
  src/main/java/com/chone/server/domains/order/repository/OrderRepository.java
  src/main/java/com/chone/server/domains/order/service/OrderService.java
Labels: ❤️‍🔥Feat

#53 Feat: 리뷰 목록, 상세 목록 조회 API 구현
  src/main/java/com/chone/server/domains/order/service/OrderDomainService.java
  src/main/java/com/chone/server/domains/review/controller/ReviewController.java
  src/main/java/com/chone/server/domains/review/dto/request/CreateRequestDto.java
  src/main/java/com/chone/server/domains/review/dto/request/ReviewListRequestDto.java
  src/main/java/com/chone/server/domains/review/dto/response/PageInfoDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewDetailResponseDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewListResponseDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewPageResponseDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewReadResponseDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewResponseDto.java
  src/main/java/com/chone/server/domains/review/exception/ReviewExceptionCode.java
  src/main/java/com/chone/server/domains/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/chone/server/domains/review/repository/ReviewSearchRepository.java
  src/main/java/com/chone/server/domains/review/service/ReviewService.java
Labels: ❤️‍🔥Feat

#60 Feat: 주문 삭제 기능 구현
  src/main/java/com/chone/server/domains/order/controller/OrderController.java
  src/main/java/com/chone/server/domains/order/domain/Order.java
  src/main/java/com/chone/server/domains/order/dto/response/DeleteOrderResponse.java
  src/main/java/com/chone/server/domains/order/exception/OrderExceptionCode.java
  src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderDetailSearchRepositoryImpl.java
  src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderJpaRepository.java
  src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderListSearchRepositoryImpl.java
  src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderRepositoryImpl.java
  src/main/java/com/chone/server/domains/order/service/OrderDomainService.java
  src/main/java/com/chone/server/domains/order/service/OrderService.java
Labels: ❤️‍🔥Feat, 🔥 Refactor

#61 Feat: 리뷰 수정 API 구현
  .github/workflows/main.yml
  build.gradle
  src/main/java/com/chone/server/domains/review/controller/ReviewController.java
  src/main/java/com/chone/server/domains/review/domain/Review.java
  src/main/java/com/chone/server/domains/review/dto/request/UpdateRequestDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewUpdateResponseDto.java
  src/main/java/com/chone/server/domains/review/exception/ReviewExceptionCode.java
  src/main/java/com/chone/server/domains/review/service/ReviewService.java
Labels: ❤️‍🔥Feat

#63 Feat: Security 설정 및 회원 CRUD 구현
  src/main/java/com/chone/server/commons/config/SecurityConfig.java
  src/main/java/com/chone/server/commons/jwt/JwtUtil.java
  src/main/java/com/chone/server/domains/auth/dto/CustomUserDetails.java
  src/main/java/com/chone/server/domains/auth/dto/LoginDto.java
  src/main/java/com/chone/server/domains/auth/filter/JwtFilter.java
  src/main/java/com/chone/server/domains/auth/filter/LoginFilter.java
  src/main/java/com/chone/server/domains/auth/service/CustomUserDetailsService.java
  src/main/java/com/chone/server/domains/auth/service/MockUserDetailsServiceImpl.java
  src/main/java/com/chone/server/domains/user/controller/UserController.java
  src/main/java/com/chone/server/domains/user/domain/Role.java
  src/main/java/com/chone/server/domains/user/domain/User.java
  src/main/java/com/chone/server/domains/user/dto/request/LoginRequestDto.java
  src/main/java/com/chone/server/domains/user/dto/request/SignupRequestDto.java
  src/main/java/com/chone/server/domains/user/dto/request/UserRoleUpdateRequestDto.java
  src/main/java/com/chone/server/domains/user/dto/request/UserUpdateRequestDto.java
  src/main/java/com/chone/server/domains/user/dto/response/LoginResponseDto.java
  src/main/java/com/chone/server/domains/user/dto/response/UserResponseDto.java
  src/main/java/com/chone/server/domains/user/exception/UserExceptionCode.java
  src/main/java/com/chone/server/domains/user/repository/UserRepository.java
  src/main/java/com/chone/server/domains/user/service/UserService.java
Labels: ❤️‍🔥Feat

#66 Feat: 리뷰 삭제 API 추가
  src/main/java/com/chone/server/domains/review/controller/ReviewController.java
  src/main/java/com/chone/server/domains/review/domain/Review.java
  src/main/java/com/chone/server/domains/review/dto/request/DeleteRequestDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewDeleteResponseDto.java
  src/main/java/com/chone/server/domains/review/exception/ReviewExceptionCode.java
  src/main/java/com/chone/server/domains/review/repository/ReviewRepository.java
  src/main/java/com/chone/server/domains/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/chone/server/domains/review/repository/ReviewSearchRepository.java
  src/main/java/com/chone/server/domains/review/service/ReviewService.java
Labels: ❤️‍🔥Feat

#67 Feat: S3 이미지 삭제 기능 및 깃허브 액션 일시정지
  .github/workflows/main.yml
  src/main/java/com/chone/server/domains/s3/service/S3Service.java
Labels: ❤️‍🔥Feat

#68 Update: Product 에 상품 이미지 기능 추가
  src/main/java/com/chone/server/domains/product/controller/ProductController.java
  src/main/java/com/chone/server/domains/product/dto/request/CreateRequestDto.java
  src/main/java/com/chone/server/domains/product/dto/request/UpdateRequestDto.java
  src/main/java/com/chone/server/domains/product/service/ProductService.java
Labels: 🔄 Update

#69 Feat: 가게별 리뷰 통계 조회 API 구현
  src/main/java/com/chone/server/domains/review/controller/ReviewController.java
  src/main/java/com/chone/server/domains/review/dto/request/StatisticsRequestDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewStatisticsResponseDto.java
  src/main/java/com/chone/server/domains/review/repository/ReviewStatisticsRepository.java
  src/main/java/com/chone/server/domains/review/repository/ReviewStatisticsRepositoryImpl.java
  src/main/java/com/chone/server/domains/review/service/ReviewService.java
Labels: ❤️‍🔥Feat

#73 Feat: 유저검색 및 페이지 처리
  src/main/java/com/chone/server/domains/auth/dto/CustomUserDetails.java
  src/main/java/com/chone/server/domains/user/controller/UserController.java
  src/main/java/com/chone/server/domains/user/domain/User.java
  src/main/java/com/chone/server/domains/user/dto/response/SearchUserResponseDto.java
  src/main/java/com/chone/server/domains/user/dto/response/UserResponseDto.java
  src/main/java/com/chone/server/domains/user/repository/UserRepository.java
  src/main/java/com/chone/server/domains/user/repository/custom/UserRepositoryCustom.java
  src/main/java/com/chone/server/domains/user/repository/custom/UserRepositoryCustomImpl.java
  src/main/java/com/chone/server/domains/user/service/UserService.java
Labels: ❤️‍🔥Feat

#74 Refactor: 다중 정렬 기능 추가
  src/main/java/com/chone/server/domains/review/repository/ReviewRepositoryImpl.java
Labels: 🔥 Refactor

#76 Feat: 결제 내역 목록 조회 구현
  src/main/java/com/chone/server/domains/auth/dto/CustomUserDetails.java
  src/main/java/com/chone/server/domains/order/dto/request/OrderFilterParams.java
  src/main/java/com/chone/server/domains/order/exception/OrderExceptionCode.java
  src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderListSearchRepositoryImpl.java
  src/main/java/com/chone/server/domains/order/service/OrderService.java
  src/main/java/com/chone/server/domains/payment/controller/PaymentController.java
  src/main/java/com/chone/server/domains/payment/dto/request/PaymentFilterParams.java
  src/main/java/com/chone/server/domains/payment/dto/response/PaymentPageResponse.java
  src/main/java/com/chone/server/domains/payment/exception/PaymentExceptionCode.java
  src/main/java/com/chone/server/domains/payment/infrastructure/jpa/PaymentListSearchRepositoryImpl.java
  src/main/java/com/chone/server/domains/payment/infrastructure/jpa/PaymentRepositoryImpl.java
  src/main/java/com/chone/server/domains/payment/repository/PaymentListSearchRepository.java
  src/main/java/com/chone/server/domains/payment/repository/PaymentRepository.java
  src/main/java/com/chone/server/domains/payment/service/PaymentService.java
  src/main/java/com/chone/server/domains/user/domain/User.java
Labels: ❤️‍🔥Feat

#79 Refactor: Review 상세 조회 로직 리팩토링
  src/main/java/com/chone/server/domains/review/dto/response/ReviewDetailResponseDto.java
  src/main/java/com/chone/server/domains/review/repository/ReviewDetailRepositoryImpl.java
  src/main/java/com/chone/server/domains/review/repository/ReviewDetailSearchRepository.java
  src/main/java/com/chone/server/domains/review/service/ReviewService.java
Labels: 🔥 Refactor

#81 Feat: User ID로 전체 리뷰 조회
  src/main/java/com/chone/server/commons/facade/ReviewFacade.java
  src/main/java/com/chone/server/domains/review/facade/ReviewFacadeImpl.java
  src/main/java/com/chone/server/domains/review/repository/ReviewRepository.java
  src/main/java/com/chone/server/domains/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/chone/server/domains/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/chone/server/domains/review/repository/ReviewSearchRepositoryImpl.java
  src/main/java/com/chone/server/domains/review/service/ReviewService.java
Labels: ❤️‍🔥Feat

#83 Refactor: Review Facade Pattern 적용
  src/main/java/com/chone/server/commons/facade/ReviewFacade.java
  src/main/java/com/chone/server/domains/review/controller/ReviewController.java
  src/main/java/com/chone/server/domains/review/facade/ReviewFacadeImpl.java
  src/main/java/com/chone/server/domains/review/infrastructure/jpa/ReviewDetailRepositoryImpl.java
  src/main/java/com/chone/server/domains/review/infrastructure/jpa/ReviewRepositoryImpl.java
  src/main/java/com/chone/server/domains/review/infrastructure/jpa/ReviewSearchRepositoryImpl.java
  src/main/java/com/chone/server/domains/review/infrastructure/jpa/ReviewStatisticsRepositoryImpl.java
  src/main/java/com/chone/server/domains/review/service/ReviewService.java
Labels: 🔥 Refactor

#86 Feat: Product, Store 도메인에 Facade 패턴 적용
  src/main/java/com/chone/server/commons/facade/ProductFacade.java
  src/main/java/com/chone/server/commons/facade/StoreFacade.java
  src/main/java/com/chone/server/domains/order/service/OrderService.java
  src/main/java/com/chone/server/domains/product/controller/ProductController.java
  src/main/java/com/chone/server/domains/product/facade/ProductFacadeImpl.java
  src/main/java/com/chone/server/domains/product/repository/ProductRepository.java
  src/main/java/com/chone/server/domains/product/service/ProductService.java
  src/main/java/com/chone/server/domains/store/controller/StoreController.java
  src/main/java/com/chone/server/domains/store/facade/StoreFacadeImpl.java
  src/main/java/com/chone/server/domains/store/repository/StoreRepository.java
  src/main/java/com/chone/server/domains/store/service/StoreService.java
  src/main/java/com/chone/server/domains/user/service/UserService.java
Labels: ❤️‍🔥Feat, 🔥 Refactor

#88 Feat: 결제 취소 기능 구현
  src/main/java/com/chone/server/domains/order/domain/OrderCancelReason.java
  src/main/java/com/chone/server/domains/order/exception/OrderExceptionCode.java
  src/main/java/com/chone/server/domains/order/service/OrderDomainService.java
  src/main/java/com/chone/server/domains/payment/controller/PaymentController.java
  src/main/java/com/chone/server/domains/payment/domain/PaymentStatus.java
  src/main/java/com/chone/server/domains/payment/domain/PgPaymentLog.java
  src/main/java/com/chone/server/domains/payment/domain/PgStatus.java
  src/main/java/com/chone/server/domains/payment/dto/request/CancelPaymentRequest.java
  src/main/java/com/chone/server/domains/payment/dto/response/CancelPaymentResponse.java
  src/main/java/com/chone/server/domains/payment/dto/response/PaymentDetailResponse.java
  src/main/java/com/chone/server/domains/payment/exception/PaymentExceptionCode.java
  src/main/java/com/chone/server/domains/payment/infrastructure/jpa/PgPaymentLogJpaRepository.java
  src/main/java/com/chone/server/domains/payment/infrastructure/jpa/PgPaymentLogRepositoryImpl.java
  src/main/java/com/chone/server/domains/payment/infrastructure/pg/PgApiService.java
  src/main/java/com/chone/server/domains/payment/repository/PgPaymentLogRepository.java
  src/main/java/com/chone/server/domains/payment/service/PaymentCancellationService.java
  src/main/java/com/chone/server/domains/payment/service/PaymentDomainService.java
  src/main/java/com/chone/server/domains/payment/service/PaymentProcessService.java
  src/main/java/com/chone/server/domains/payment/service/PaymentReadService.java
  src/main/java/com/chone/server/domains/user/domain/User.java
Labels: ❤️‍🔥Feat

#91 Feat: User삭제시 연관데이터도 함께 삭제
  src/main/java/com/chone/server/commons/facade/OrderFacade.java
  src/main/java/com/chone/server/commons/facade/ReviewFacade.java
  src/main/java/com/chone/server/domains/order/facade/OrderFacadeImpl.java
  src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderJpaRepository.java
  src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderRepositoryImpl.java
  src/main/java/com/chone/server/domains/order/repository/OrderRepository.java
  src/main/java/com/chone/server/domains/review/facade/ReviewFacadeImpl.java
  src/main/java/com/chone/server/domains/user/service/UserService.java
Labels: ❤️‍🔥Feat

#94 Refactor: 주문 및 결제 관련 코드 리팩토링
  src/main/java/com/chone/server/commons/facade/OrderFacade.java
  src/main/java/com/chone/server/domains/order/controller/OrderController.java
  src/main/java/com/chone/server/domains/order/domain/OrderStatus.java
  src/main/java/com/chone/server/domains/order/domain/OrderType.java
  src/main/java/com/chone/server/domains/order/exception/OrderExceptionCode.java
  src/main/java/com/chone/server/domains/order/facade/OrderFacadeImpl.java
  src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderJpaRepository.java
  src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderRepositoryImpl.java
  src/main/java/com/chone/server/domains/order/repository/OrderRepository.java
  src/main/java/com/chone/server/domains/order/service/OrderCancellationService.java
  src/main/java/com/chone/server/domains/order/service/OrderCreationService.java
  src/main/java/com/chone/server/domains/order/service/OrderDeletionService.java
  src/main/java/com/chone/server/domains/order/service/OrderDomainService.java
  src/main/java/com/chone/server/domains/order/service/OrderReadService.java
  src/main/java/com/chone/server/domains/order/service/OrderService.java
  src/main/java/com/chone/server/domains/order/service/OrderUpdateService.java
  src/main/java/com/chone/server/domains/payment/domain/PaymentStatus.java
  src/main/java/com/chone/server/domains/payment/exception/PaymentExceptionCode.java
  src/main/java/com/chone/server/domains/payment/service/PaymentCancellationService.java
  src/main/java/com/chone/server/domains/payment/service/PaymentDomainService.java
  src/main/java/com/chone/server/domains/payment/service/PaymentProcessService.java
  src/main/java/com/chone/server/domains/user/domain/Role.java
Labels: 🔥 Refactor

#95 Feat: User에 Swagger 적용
  build.gradle
  src/main/java/com/chone/server/commons/config/SecurityConfig.java
  src/main/java/com/chone/server/commons/config/SwaggerConfig.java
  src/main/java/com/chone/server/domains/auth/filter/JwtFilter.java
  src/main/java/com/chone/server/domains/user/base/BaseResponseBody.java
  src/main/java/com/chone/server/domains/user/base/DataResponseBody.java
  src/main/java/com/chone/server/domains/user/controller/UserController.java
  src/main/java/com/chone/server/domains/user/dto/request/LoginRequestDto.java
  src/main/java/com/chone/server/domains/user/dto/request/SignupRequestDto.java
  src/main/java/com/chone/server/domains/user/dto/request/UserRoleUpdateRequestDto.java
  src/main/java/com/chone/server/domains/user/dto/request/UserUpdateRequestDto.java
  src/main/java/com/chone/server/domains/user/dto/response/LoginResponseDto.java
  src/main/java/com/chone/server/domains/user/dto/response/PageInfoDto.java
  src/main/java/com/chone/server/domains/user/dto/response/ReadResponseDto.java
  src/main/java/com/chone/server/domains/user/dto/response/SearchUserResponseDto.java
  src/main/java/com/chone/server/domains/user/dto/response/UserResponseDto.java
  src/main/java/com/chone/server/domains/user/exception/UserExceptionCode.java
  src/main/java/com/chone/server/domains/user/facade/UserFacadeImpl.java
  src/main/java/com/chone/server/domains/user/repository/UserRepository.java
  src/main/java/com/chone/server/domains/user/repository/custom/UserRepositoryCustom.java
  src/main/java/com/chone/server/domains/user/repository/custom/UserRepositoryCustomImpl.java
  src/main/java/com/chone/server/domains/user/service/UserService.java
Labels: ❤️‍🔥Feat, 🔥 Refactor

#97 Refactor: Ai, Review에 Facade 패턴 적용 및 비즈니스 로직 리팩토링
  src/main/java/com/chone/server/commons/facade/AiFacade.java
  src/main/java/com/chone/server/commons/facade/ProductFacade.java
  src/main/java/com/chone/server/commons/facade/ReviewFacade.java
  src/main/java/com/chone/server/domains/ai/facade/AiFacadeImpl.java
  src/main/java/com/chone/server/domains/ai/service/AiService.java
  src/main/java/com/chone/server/domains/product/facade/ProductFacadeImpl.java
  src/main/java/com/chone/server/domains/review/facade/ReviewFacadeImpl.java
  src/main/java/com/chone/server/domains/review/service/ReviewService.java
Labels: 🔥 Refactor

#100 Docs: Product, Store Swagger 설명 추가
  src/main/java/com/chone/server/domains/product/controller/ProductController.java
  src/main/java/com/chone/server/domains/product/service/ProductService.java
  src/main/java/com/chone/server/domains/store/controller/StoreController.java
Labels: 📖 Docs

#102 Docs: Ai, Review Swagger 문서화 작업
  src/main/java/com/chone/server/domains/ai/controller/AiController.java
  src/main/java/com/chone/server/domains/ai/dto/request/AiRequestDto.java
  src/main/java/com/chone/server/domains/ai/dto/request/GeminiApiRequestDto.java
  src/main/java/com/chone/server/domains/ai/dto/request/GeminiRequestDto.java
  src/main/java/com/chone/server/domains/ai/dto/response/AiResponseDto.java
  src/main/java/com/chone/server/domains/ai/dto/response/GeminiApiResponseDto.java
  src/main/java/com/chone/server/domains/ai/dto/response/GeminiResponseDto.java
  src/main/java/com/chone/server/domains/review/controller/ReviewController.java
  src/main/java/com/chone/server/domains/review/dto/request/CreateRequestDto.java
  src/main/java/com/chone/server/domains/review/dto/request/DeleteRequestDto.java
  src/main/java/com/chone/server/domains/review/dto/request/ReviewListRequestDto.java
  src/main/java/com/chone/server/domains/review/dto/request/StatisticsRequestDto.java
  src/main/java/com/chone/server/domains/review/dto/request/UpdateRequestDto.java
  src/main/java/com/chone/server/domains/review/dto/response/PageInfoDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewDeleteResponseDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewDetailResponseDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewListResponseDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewPageResponseDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewReadResponseDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewResponseDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewStatisticsResponseDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewUpdateResponseDto.java
  src/main/resources/application.yml
Labels: 📖 Docs

#101 Update: S3 에서 이미지 삭제시 null 처리 추가
  src/main/java/com/chone/server/domains/s3/service/S3Service.java
Labels: 🔄 Update

#106 Fix: 이미지 S3 업로드 및 페이징 기본값 설정
  src/main/java/com/chone/server/domains/review/controller/ReviewController.java
  src/main/java/com/chone/server/domains/review/dto/request/ReviewListRequestDto.java
  src/main/java/com/chone/server/domains/review/facade/ReviewFacadeImpl.java
  src/main/java/com/chone/server/domains/review/service/ReviewService.java
Labels: ⚒️ Fix, 🔥 Refactor

#108 Fix: 가게, 상품 도메인
  src/main/java/com/chone/server/domains/s3/service/S3Service.java
  src/main/java/com/chone/server/domains/store/dto/request/CreateRequestDto.java
  src/main/java/com/chone/server/domains/store/dto/request/PutRequestDto.java
  src/main/java/com/chone/server/domains/store/dto/request/UpdateRequestDto.java
  src/main/java/com/chone/server/domains/store/exception/StoreExceptionCode.java
  src/main/java/com/chone/server/domains/store/facade/StoreFacadeImpl.java
  src/main/java/com/chone/server/domains/store/service/StoreService.java
Labels: ⚒️ Fix

#110 Refactor: Product, Store DTO 수정
  src/main/java/com/chone/server/domains/product/dto/request/CreateRequestDto.java
  src/main/java/com/chone/server/domains/product/dto/request/UpdateRequestDto.java
  src/main/java/com/chone/server/domains/product/dto/response/CreateResponseDto.java
  src/main/java/com/chone/server/domains/product/dto/response/PageInfoDto.java
  src/main/java/com/chone/server/domains/product/dto/response/ReadResponseDto.java
  src/main/java/com/chone/server/domains/product/dto/response/SearchResponseDto.java
  src/main/java/com/chone/server/domains/store/dto/request/CreateRequestDto.java
  src/main/java/com/chone/server/domains/store/dto/request/UpdateRequestDto.java
  src/main/java/com/chone/server/domains/store/dto/response/CreateResponseDto.java
  src/main/java/com/chone/server/domains/store/dto/response/PageInfoDto.java
  src/main/java/com/chone/server/domains/store/dto/response/ReadResponseDto.java
  src/main/java/com/chone/server/domains/store/dto/response/SearchResponseDto.java
Labels: 🔥 Refactor

#113 Test: Ai, Review Test Code 및 코드 리팩토링
  build.gradle
  src/main/java/com/chone/server/domains/ai/controller/AiController.java
  src/main/java/com/chone/server/domains/ai/dto/request/AiRequestDto.java
  src/main/java/com/chone/server/domains/review/controller/ReviewController.java
  src/main/java/com/chone/server/domains/review/dto/request/CreateRequestDto.java
  src/main/java/com/chone/server/domains/review/dto/request/ReviewListRequestDto.java
  src/main/java/com/chone/server/domains/review/dto/response/ReviewPageResponseDto.java
  src/main/java/com/chone/server/domains/review/service/ReviewService.java
  src/test/java/com/chone/server/domains/ai/controller/AiControllerTest.java
  src/test/java/com/chone/server/domains/review/controller/ReviewControllerTest.java
Labels: ⚒️ Fix, 🔥 Refactor, ⚗️Test

#116 Fix: Review 조회 시 N+1 문제 해결
  src/main/java/com/chone/server/domains/review/infrastructure/jpa/ReviewRepositoryImpl.java
  src/main/java/com/chone/server/domains/review/infrastructure/jpa/ReviewSearchRepositoryImpl.java
Labels: ⚒️ Fix

#117 Refactor: Review 통계 로직 Facade로 리팩토링
  src/main/java/com/chone/server/commons/facade/ReviewFacade.java
  src/main/java/com/chone/server/domains/review/facade/ReviewFacadeImpl.java
  src/main/java/com/chone/server/domains/review/service/ReviewService.java
Labels: 🔥 Refactor
